plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'com.gradleup.shadow' version '9.0.0-beta4'
}

group = 'com.yunusoksuz'
version = '1.0-SNAPSHOT'

def mainClassName = 'com.yunusoksuz.tcpproxy.AppMain'
import org.apache.tools.ant.filters.ReplaceTokens

def port = project.hasProperty("port") ? project.property("port") : '5000'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-simple:1.7.25'
    testImplementation group: 'junit', name: 'junit', version: '4.11'
}

tasks.register('replacePort', Copy) {
    from('.') {
        include 'Dockerfile.dist'
        rename 'Dockerfile.dist', 'Dockerfile'
        filter(ReplaceTokens, tokens: ['PORT': port])
    }
    into('.')
}

tasks.named('compileJava').configure { mustRunAfter('replacePort') }
tasks.named('processResources').configure { mustRunAfter('replacePort') }
tasks.findByName('processTestResources')?.mustRunAfter('replacePort')
tasks.named('jar').configure { mustRunAfter('replacePort') }

shadowJar {
    archiveBaseName = 'tcp-proxy'
    archiveClassifier = ''
    archiveVersion = ''
    manifest {
        attributes 'Main-Class': mainClassName
    }
}

build {
    dependsOn replacePort
}

build.finalizedBy shadowJar
